### ISSUE TITLE
X [ERROR] Could not resolve "./Color-Picker"

### ISSUE THREAD

**Issue by qzdy-cmyk** [battleaxedotco/brutalism#47]
I am here https://github.com/hyperbrew/bolt-cep Components used in the Vue3 project:

```
<script setup>
import { Grid } from "brutalism";
</script>

<template>
        <Grid></Grid>
</template>


```

Project error：
```
X [ERROR] Could not resolve "./Color-Picker"

    node_modules/brutalism/components/Color-Picker/index.js:1:23:
      1 │ export default require("./Color-Picker").default;
        ╵                        ~~~~~~~~~~~~~~~~

18:52:00 [vite] error while updating dependencies:
Error: Build failed with 1 error:
node_modules/brutalism/components/Color-Picker/index.js:1:23: ERROR: Could not resolve "./Color-Picker"      
    at failureErrorWithLog (F:\qzdyplus\2\qzdyy\node_modules\esbuild\lib\main.js:1649:15)
    at F:\qzdyplus\2\qzdyy\node_modules\esbuild\lib\main.js:1058:25
    at F:\qzdyplus\2\qzdyy\node_modules\esbuild\lib\main.js:1525:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by Inventsable** [comment]
Brutalism is Vue 2, not compatible with Vue 3
